# MySQL connection properties
#LOOK IN APPCONFIG.JAVA
spring.jpa1.hibernate.ddl-auto=validate
spring.jpa1.properties.hibernate.connection.provider_class = org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
spring.jpa1.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa1.properties.hibernate.connection.url=jdbc:mysql://capline.cs2m1j2gr4iq.us-east-2.rds.amazonaws.com:3306/rule_engine?useSSL=false
spring.jpa1.properties.hibernate.connection.username=capline_user
spring.jpa1.properties.hibernate.connection.password=capline_user115!!%

spring.datasource1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa1.properties.hibernate.id.new_generator_mappings = false
spring.jpa1.properties.hibernate.format_sql = true
spring.jpa1.show-sql=true


# Hibernate properties
#hibernate.show_sql=true
#hibernate.hbm2ddl.auto=update 

#C3P0 properties
# c3p0  pooling
hibernate.c3p01.max_size=20
hibernate.c3p01.min_size=5
hibernate.c3p01.idle_test_period=60000
hibernate.c3p01.acquire_increment=1
hibernate.c3p01.timeout=1800
hibernate.c3p01.max_statements=150

entitymanager.packagesToScan=com.tricon.ruleengine.model
#JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

##security.ignored:*.bundle.*
##security:
  ##ignored:
  ##- "*.bundle.*"
#jwt  
jwt.header=Authorization
jwt.secret=mySecretLocal
jwt.expiration=600000
jwt.route.authentication.path=/account/login
jwt.route.authentication.refresh=/refresh

#Google Sheet related Server 
google.credential.folder=/opt/project/tricon/files
google.client.secret=/opt/project/tricon/files/client_secret.json
app.debug.folder=/opt/project/tricon/log/


#share Point
#sharepoint.appid=1aa3a3f8-6818-4e77-85f7-abba8ba27d33
#sharepoint.apppassword=hvehsCQIME9-[=ciLO6721@
#sharepoint.redirecturl=http://localhost:8080/readDriveSuc

#application.url=http://18.223.22.149
application.url=https://www.caplineruleengine.com

#application.url=http://18.....:8080

application.sharepoint.init=/sharePointIni


## Logging
logging.level.org.springframework.web=ERROR
logging.level.com.tricon.ruleengine=DEBUG
logging.file=/opt/project/tricon/log/ruleengine.log

#logging.pattern.console= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#Eagle soft
#es.esport=2638
es.ssl.client.password=p@ssw0rd
es.ssl.client.certificate.trustStore=/opt/project/tricon/client/cacerts.jks
es.ssl.client.certificate.keyStore=/opt/project/tricon/client/keystore.jks
re.admin=admin_admin
re.xslt.path=/opt/project/tricon/xml/
re.xslt.file=/opt/project/tricon/xml/pdfformat.xslt
re.xsltos.file=/opt/project/tricon/xml/pdfformat_os.xslt
re.xslt.filenew=/opt/project/tricon/xml/new_pdfformat.xslt
google.chorme.driver=/opt/project/tricon/chrome/chromedriver
rule.save.report.data=true
server:
  port: 8443
  ssl:
    enabled: true