# MySQL connection properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.provider_class = org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.connection.url=jdbc:mysql://192.168.1.73:3306/rule_engine_1?useSSL=false
spring.jpa.properties.hibernate.connection.username=newuser1
spring.jpa.properties.hibernate.connection.password=root@12345%
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.show-sql=false


# Hibernate properties
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update 

#C3P0 properties
# c3p0  pooling
hibernate.c3p0.max_size=20
hibernate.c3p0.min_size=5
hibernate.c3p0.idle_test_period=600
hibernate.c3p0.acquire_increment=1
hibernate.c3p0.timeout=1800
hibernate.c3p0.max_statements=150

entitymanager.packagesToScan=com.tricon.ruleengine.model
#JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#####
google.client_secret=d:/Project/Tricon/TimeEstimates/IV rule engine/Code Related/3/client_secret.json
google.server_credentials=d:/Project/Tricon/TimeEstimates/IV rule engine/Code Related/3
#####
##security.ignored:*.bundle.*
##security:
  ##ignored:
  ##- "*.bundle.*"
#jwt  
jwt.header=Authorization
jwt.secret=mySecretLocal
jwt.expiration=60000
jwt.route.authentication.path=/account/login
jwt.route.authentication.refresh=/refresh

#Google Sheet related 
google.credential.folder=E:/Project/Tricon/files
google.client.secret=E:/Project/Tricon/files/client_secret.json
