package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdaCodes generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "ada_codes")
public class AdaCodes implements java.io.Serializable {

	private static final long serialVersionUID = -1788136059964681679L;
	private int id;
	private String code;
	private String description;

	public AdaCodes() {
	}

	public AdaCodes(int id) {
		this.id = id;
	}

	public AdaCodes(int id, String code, String description) {
		this.id = id;
		this.code = code;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
