package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GoogleSheets generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "google_sheets", uniqueConstraints=
@UniqueConstraint(columnNames={"sheet_name", "app_sheet_name"}))
public class GoogleSheets extends BaseAudit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8400768077034656443L;
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@Column(name = "sheet_id", length = 45)
	private String sheetId;
	@Column(name = "sheet_name")
	private String sheetName;
	@Column(name = "app_sheet_name", length = 45)
	private String appSheetName;
	private Integer officeId;

	public GoogleSheets() {
	}

	public GoogleSheets(int id) {
		this.id = id;
	}

	public GoogleSheets(int id, String sheetId, String sheetName, String appSheetName, Integer officeId) {
		this.id = id;
		this.sheetId = sheetId;
		this.sheetName = sheetName;
		this.appSheetName = appSheetName;
		this.officeId = officeId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSheetId() {
		return this.sheetId;
	}

	public void setSheetId(String sheetId) {
		this.sheetId = sheetId;
	}

	public String getSheetName() {
		return this.sheetName;
	}

	public void setSheetName(String sheetName) {
		this.sheetName = sheetName;
	}

	public String getAppSheetName() {
		return this.appSheetName;
	}

	public void setAppSheetName(String appSheetName) {
		this.appSheetName = appSheetName;
	}

	@Column(name = "office_id")
	public Integer getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(Integer officeId) {
		this.officeId = officeId;
	}

}
