package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GoogleSheets generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "google_sheets")
public class GoogleSheets implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8400768077034656443L;
	private int id;
	private String sheetId;
	private String sheetName;
	private String description;
	private Integer officeId;

	public GoogleSheets() {
	}

	public GoogleSheets(int id) {
		this.id = id;
	}

	public GoogleSheets(int id, String sheetId, String sheetName, String description, Integer officeId) {
		this.id = id;
		this.sheetId = sheetId;
		this.sheetName = sheetName;
		this.description = description;
		this.officeId = officeId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "sheet_id", length = 45)
	public String getSheetId() {
		return this.sheetId;
	}

	public void setSheetId(String sheetId) {
		this.sheetId = sheetId;
	}

	@Column(name = "sheet_name")
	public String getSheetName() {
		return this.sheetName;
	}

	public void setSheetName(String sheetName) {
		this.sheetName = sheetName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "office_id")
	public Integer getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(Integer officeId) {
		this.officeId = officeId;
	}

}
