package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IvfCategory generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "ivf_category")
public class IvfCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7303212725120925879L;
	private int id;
	private String name;

	public IvfCategory() {
	}

	public IvfCategory(int id) {
		this.id = id;
	}

	public IvfCategory(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
