package com.tricon.ruleengine.model.db;
//Generated May 3, 2018 4:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
* IVFDefaultValue generated by hbm2java
* @author Deepak.Dogra
*
*/
@Entity
@Table(name = "ivf_default_value",uniqueConstraints = {	@UniqueConstraint(columnNames = {"field_name"}) })
public class IVFDefaultValue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1696739915439062168L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@Column(name = "code")
	private String code;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "field_name")
	private String fieldName;

	
	@Column(name = "get_name")
	private String getName;

	@Column(name = "set_name")
	private String setName;
	
	@Column(name = "default_value")
	private String defaultValue;


	@Column(name = "active")
	private int active;


	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public String getCode() {
		return code;
	}


	public void setCode(String code) {
		this.code = code;
	}


	public String getFieldName() {
		return fieldName;
	}


	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}


	public String getGetName() {
		return getName;
	}


	public void setGetName(String getName) {
		this.getName = getName;
	}


	public String getSetName() {
		return setName;
	}


	public void setSetName(String setName) {
		this.setName = setName;
	}


	public String getDefaultValue() {
		return defaultValue;
	}


	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}


	public int getActive() {
		return active;
	}


	public void setActive(int active) {
		this.active = active;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}



}
