package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IvfFields generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "ivf_fields")
public class IvfFields implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2238191695243052179L;
	private int id;
	private IvfCategory ivfCategory;
	private String fieldName;

	public IvfFields() {
	}

	public IvfFields(int id) {
		this.id = id;
	}

	public IvfFields(int id, IvfCategory ivfCategory, String fieldName) {
		this.id = id;
		this.ivfCategory = ivfCategory;
		this.fieldName = fieldName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ivf_category_id")
	public IvfCategory getIvfCategory() {
		return this.ivfCategory;
	}

	public void setIvfCategory(IvfCategory ivfCategory) {
		this.ivfCategory = ivfCategory;
	}

	@Column(name = "field_name")
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

}
