package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdaCodes generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "iv_form_type")
public class IVFormType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7141996059685978572L;
	private int id;
	private String name;
	private String description;

	public IVFormType() {
	}

	public IVFormType(int id) {
		this.id = id;
	}

	public IVFormType(int id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name",unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
