package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mappings generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "mappings_1")
public class Mappings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8325067135795801332L;
	private int id;
	private AdaCodes adaCodes;
	private ServiceCodeCategory serviceCodeCategory;
	private String coveredUnderMedical;
	private String downgrading;
	private String toothNoForDowngrading;
	private String fillingToothNoMapping;
	private String freqencyLimitationApplicable;
	private String missingToothClauseApplicable;
	private String bundlingApplicable;
	private String additionalInformationNeeded;
	private String preAuthNeeded;
	private String ageLimitApplicable;

	public Mappings() {
	}

	public Mappings(int id) {
		this.id = id;
	}

	public Mappings(int id, AdaCodes adaCodes, ServiceCodeCategory serviceCodeCategory, String coveredUnderMedical,
			String downgrading, String toothNoForDowngrading, String fillingToothNoMapping,
			String freqencyLimitationApplicable, String missingToothClauseApplicable, String bundlingApplicable,
			String additionalInformationNeeded, String preAuthNeeded, String ageLimitApplicable) {
		this.id = id;
		this.adaCodes = adaCodes;
		this.serviceCodeCategory = serviceCodeCategory;
		this.coveredUnderMedical = coveredUnderMedical;
		this.downgrading = downgrading;
		this.toothNoForDowngrading = toothNoForDowngrading;
		this.fillingToothNoMapping = fillingToothNoMapping;
		this.freqencyLimitationApplicable = freqencyLimitationApplicable;
		this.missingToothClauseApplicable = missingToothClauseApplicable;
		this.bundlingApplicable = bundlingApplicable;
		this.additionalInformationNeeded = additionalInformationNeeded;
		this.preAuthNeeded = preAuthNeeded;
		this.ageLimitApplicable = ageLimitApplicable;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ada_codes_id")
	public AdaCodes getAdaCodes() {
		return this.adaCodes;
	}

	public void setAdaCodes(AdaCodes adaCodes) {
		this.adaCodes = adaCodes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_code_category_id")
	public ServiceCodeCategory getServiceCodeCategory() {
		return this.serviceCodeCategory;
	}

	public void setServiceCodeCategory(ServiceCodeCategory serviceCodeCategory) {
		this.serviceCodeCategory = serviceCodeCategory;
	}

	@Column(name = "covered_under_medical")
	public String getCoveredUnderMedical() {
		return this.coveredUnderMedical;
	}

	public void setCoveredUnderMedical(String coveredUnderMedical) {
		this.coveredUnderMedical = coveredUnderMedical;
	}

	@Column(name = "downgrading")
	public String getDowngrading() {
		return this.downgrading;
	}

	public void setDowngrading(String downgrading) {
		this.downgrading = downgrading;
	}

	@Column(name = "toothNo_for_downgrading", columnDefinition = "text")
	public String getToothNoForDowngrading() {
		return this.toothNoForDowngrading;
	}

	public void setToothNoForDowngrading(String toothNoForDowngrading) {
		this.toothNoForDowngrading = toothNoForDowngrading;
	}

	@Column(name = "filling_tooth_no_mapping", columnDefinition = "text")
	public String getFillingToothNoMapping() {
		return this.fillingToothNoMapping;
	}

	public void setFillingToothNoMapping(String fillingToothNoMapping) {
		this.fillingToothNoMapping = fillingToothNoMapping;
	}

	@Column(name = "freqency_limitation_applicable")
	public String getFreqencyLimitationApplicable() {
		return this.freqencyLimitationApplicable;
	}

	public void setFreqencyLimitationApplicable(String freqencyLimitationApplicable) {
		this.freqencyLimitationApplicable = freqencyLimitationApplicable;
	}

	@Column(name = "missing_tooth_clause_applicable")
	public String getMissingToothClauseApplicable() {
		return this.missingToothClauseApplicable;
	}

	public void setMissingToothClauseApplicable(String missingToothClauseApplicable) {
		this.missingToothClauseApplicable = missingToothClauseApplicable;
	}

	@Column(name = "bundling_applicable")
	public String getBundlingApplicable() {
		return this.bundlingApplicable;
	}

	public void setBundlingApplicable(String bundlingApplicable) {
		this.bundlingApplicable = bundlingApplicable;
	}

	@Column(name = "additional_information_needed", columnDefinition = "text")
	public String getAdditionalInformationNeeded() {
		return this.additionalInformationNeeded;
	}

	public void setAdditionalInformationNeeded(String additionalInformationNeeded) {
		this.additionalInformationNeeded = additionalInformationNeeded;
	}

	@Column(name = "pre_auth_needed")
	public String getPreAuthNeeded() {
		return this.preAuthNeeded;
	}

	public void setPreAuthNeeded(String preAuthNeeded) {
		this.preAuthNeeded = preAuthNeeded;
	}

	@Column(name = "age_limit_applicable")
	public String getAgeLimitApplicable() {
		return this.ageLimitApplicable;
	}

	public void setAgeLimitApplicable(String ageLimitApplicable) {
		this.ageLimitApplicable = ageLimitApplicable;
	}

}
