package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Reports generated by hbm2java
 */
@Entity
@Table(name = "reports",uniqueConstraints = {//uniqueConstraints = {@UniqueConstraint(columnNames= {"first", "second"})})//, @UniqueConstraint(columnNames = "ivf_form_id"),@UniqueConstraint(columnNames = "office_id")
		@UniqueConstraint(columnNames = {"treatement_plan_id","ivf_form_id","office_id"}) })
public class Reports extends BaseAudit implements java.io.Serializable {

	private static final long serialVersionUID = -9135032927310683833L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;

	
	
	@Column(name = "treatement_plan_id", length = 45)
	private String treatementPlanId;
	@Column(name = "ivf_form_id", length = 45)
	private String ivfFormId;
	@Column(name = "patient_name", length = 255)
	private String patientName;
	@Column(name = "patient_id", length = 255)
	private String patientId;
	@Column(name = "patient_dob", length = 255)
	private String patientDob;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "office_id")
	private Office office;
	@Column(name = "group_run")
	private int groupRun;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reports")
	private Set<ReportDetail> reportDetails = new HashSet<ReportDetail>(0);

	public Reports() {
	}

	public Reports(int id) {
		this.id = id;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public String getTreatementPlanId() {
		return this.treatementPlanId;
	}

	public void setTreatementPlanId(String treatementPlanId) {
		this.treatementPlanId = treatementPlanId;
	}

	public String getIvfFormId() {
		return this.ivfFormId;
	}

	public void setIvfFormId(String ivfFormId) {
		this.ivfFormId = ivfFormId;
	}

	public Set<ReportDetail> getReportDetails() {
		return this.reportDetails;
	}

	public void setReportDetails(Set<ReportDetail> reportDetails) {
		this.reportDetails = reportDetails;
	}

	public String getPatientName() {
		return patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	public String getPatientDob() {
		return patientDob;
	}

	public void setPatientDob(String patientDob) {
		this.patientDob = patientDob;
	}

	public Office getOffice() {
		return office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}

	public int getGroupRun() {
		return groupRun;
	}

	public void setGroupRun(int groupRun) {
		this.groupRun = groupRun;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	
}
