package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**

 */
/**
 * ReportDetail generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "report_claim_detail")
public class ReportClaimDetail extends BaseAudit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9150819243860027278L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "report_id")
	private ReportsClaim reports;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_id")
	private Rules rules;
	@Column(name = "error_message", columnDefinition = "text")
	private String errorMessage;
	@Column(name = "group_run")
	private int groupRun;
	@Column(name = "report_type")
	private int reportType;
	@Column(name = "message_type")
	private int messageType;


	public ReportClaimDetail() {
	}

	public ReportClaimDetail(int id) {
		this.id = id;
	}

	public ReportClaimDetail(int id, ReportsClaim reports, Rules rules, String errorMessage) {
		this.id = id;
		this.reports = reports;
		this.rules = rules;
		this.errorMessage = errorMessage;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ReportsClaim getReports() {
		return this.reports;
	}

	public void setReports(ReportsClaim reports) {
		this.reports = reports;
	}

	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public int getGroupRun() {
		return groupRun;
	}

	public void setGroupRun(int groupRun) {
		this.groupRun = groupRun;
	}

	public int getReportType() {
		return reportType;
	}

	public void setReportType(int reportType) {
		this.reportType = reportType;
	}

	public int getMessageType() {
		return messageType;
	}

	public void setMessageType(int messageType) {
		this.messageType = messageType;
	}

	
	
}
