package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reports generated by hbm2java
 */
@Entity
@Table(name = "reports")
public class Reports extends BaseAudit implements java.io.Serializable {

	private static final long serialVersionUID = -9135032927310683833L;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@Column(name = "treatement_plan_id",unique=true, length = 45)
	private String treatementPlanId;
	@Column(name = "ivf_form_id", length = 45)
	private String ivfFormId;
	@Column(name = "patient_name", length = 255)
	private String patientName;
	@Column(name = "patient_dob", length = 255)
	private String patientDob;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reports")
	private Set<ReportDetail> reportDetails = new HashSet<ReportDetail>(0);

	public Reports() {
	}

	public Reports(int id) {
		this.id = id;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public String getTreatementPlanId() {
		return this.treatementPlanId;
	}

	public void setTreatementPlanId(String treatementPlanId) {
		this.treatementPlanId = treatementPlanId;
	}

	public String getIvfFormId() {
		return this.ivfFormId;
	}

	public void setIvfFormId(String ivfFormId) {
		this.ivfFormId = ivfFormId;
	}

	public Set<ReportDetail> getReportDetails() {
		return this.reportDetails;
	}

	public void setReportDetails(Set<ReportDetail> reportDetails) {
		this.reportDetails = reportDetails;
	}

	public String getPatientName() {
		return patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	public String getPatientDob() {
		return patientDob;
	}

	public void setPatientDob(String patientDob) {
		this.patientDob = patientDob;
	}

	
}
