package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**

 */
/**
 * ReportDetail generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "report_detail")
public class ReportDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9150819243860027278L;
	private int id;
	private Reports reports;
	private Rules rules;
	private String errorMessage;

	public ReportDetail() {
	}

	public ReportDetail(int id) {
		this.id = id;
	}

	public ReportDetail(int id, Reports reports, Rules rules, String errorMessage) {
		this.id = id;
		this.reports = reports;
		this.rules = rules;
		this.errorMessage = errorMessage;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "report_id")
	public Reports getReports() {
		return this.reports;
	}

	public void setReports(Reports reports) {
		this.reports = reports;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_id")
	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	@Column(name = "error_message", columnDefinition = "text")
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

}
