package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rules generated by hbm2java
 */
@Entity
@Table(name = "rules")
public class Rules extends BaseAudit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 489977259021273798L;
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	@Column(name = "name", columnDefinition = "text")
	private String name;
	@Column(name = "short_name", columnDefinition = "text", unique=true)
	private String shortName;
	@Column(name = "description", columnDefinition = "text")
	private String description;
	@Column(name = "active")
	private int active;
	@Column(name = "rule_type")//R= Rule Engine C= Rcm Example (R,C)
	private String ruleType;
	@Column(name = "manual_auto")
	private String manualAuto;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rules")
	private Set<ReportDetail> reportDetails = new HashSet<ReportDetail>(0);

	public Rules() {
	}

	public Rules(int id) {
		this.id = id;
	}

	public Rules(int id, String name, String description, Set<ReportDetail> reportDetails) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.reportDetails = reportDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ReportDetail> getReportDetails() {
		return this.reportDetails;
	}

	public void setReportDetails(Set<ReportDetail> reportDetails) {
		this.reportDetails = reportDetails;
	}

	public int getActive() {
		return active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getRuleType() {
		return ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getManualAuto() {
		return manualAuto;
	}

	public void setManualAuto(String manualAuto) {
		this.manualAuto = manualAuto;
	}
	
	

}
