package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rules generated by hbm2java
 */
@Entity
@Table(name = "rules")
public class Rules implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 489977259021273798L;
	private int id;
	private String name;
	private String description;
	private Set<ReportDetail> reportDetails = new HashSet<ReportDetail>(0);

	public Rules() {
	}

	public Rules(int id) {
		this.id = id;
	}

	public Rules(int id, String name, String description, Set<ReportDetail> reportDetails) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.reportDetails = reportDetails;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", columnDefinition = "text")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", columnDefinition = "text")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rules")
	public Set<ReportDetail> getReportDetails() {
		return this.reportDetails;
	}

	public void setReportDetails(Set<ReportDetail> reportDetails) {
		this.reportDetails = reportDetails;
	}

}
