package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ServiceCodeCategory generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "service_code_category")
public class ServiceCodeCategory implements java.io.Serializable {

	private static final long serialVersionUID = 4582329121161435062L;
	private int id;
	private String name;

	public ServiceCodeCategory() {
	}

	public ServiceCodeCategory(int id) {
		this.id = id;
	}

	public ServiceCodeCategory(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = " name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
