package com.tricon.ruleengine.model.db;
// Generated Jun 27, 2018 5:33:26 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeOfValues generated by hbm2java
 * @author Deepak.Dogra
 *
 */
@Entity
@Table(name = "type_of_values")
public class TypeOfValues implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8755000886533550304L;
	private int id;
	private String name;

	public TypeOfValues() {
	}

	public TypeOfValues(int id) {
		this.id = id;
	}

	public TypeOfValues(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
