spring.jpa.properties.hibernate.connection.provider_class = org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
scheduler.startcron=0 */1 * * * *
#every 12 mid night
#scheduler.startcron=0 0 */20 * * *
# Deepak
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.ruleengine-datasource.url=jdbc:mysql://localhost:3306/re_local1?useSSL=false&rewriteBatchedStatements=true
spring.ruleengine-datasource.username=root
spring.ruleengine-datasource.password=root

#spring.ruleengine-datasource.url=jdbc:mysql://capline.cs2m1j2gr4iq.us-east-2.rds.amazonaws.com:3306/rule_engine?useSSL=false
#spring.ruleengine-datasource.username=capline_user
#spring.ruleengine-datasource.password=capline_user115!!%

hibernate.hbm2ddl.auto=update
hibernate.generate_statistic=false
spring.jpa.properties.hibernate.generate_statistic=false

hibernate.order_inserts=true
hibernate.order_updates=true	
#spring.jpa.properties.hibernate.dialect=
spring.jpa.show-sql=true