spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source=metadata


#For Local MYSQL
#spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.connection.provider_class = org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcUrl = ${ES_REPLICATION_DB_URL:jdbc:mysql://localhost:3306/re_local?useSSL=false&rewriteBatchedStatements=true&characterencoding=utf-8}
spring.datasource.username = ${ES_REPLICATION_DB_USERNAME:root}
spring.datasource.password = ${ES_REPLICATION_DB_PASSWORD:root}
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
	
