spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source=metadata


#For Local MYSQL
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.connection.provider_class = org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
spring.jpa.show-sql= true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcUrl = jdbc:mysql://localhost:3306/re_local?useSSL=false&rewriteBatchedStatements=true
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
# For Rule Engine
spring.ruleengine-datasource.jdbcUrl = jdbc:mysql://localhost:3306/re_local1?useSSL=false&rewriteBatchedStatements=true
spring.ruleengine-datasource.username = root
spring.ruleengine-datasource.password = root
spring.ruleengine-datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.ruleengine-datasource.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update



spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.jdbc.batch_size=3
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true	

hibernate.generate_statistics=true
hibernate.jdbc.batch_size=4
hibernate.order_inserts=true
hibernate.order_updates=true	



spring.datasource.hibernate.generate_statistics=false
spring.datasource.hibernate.jdbc.batch_size=4
sspring.datasource.hibernate.order_inserts=true
spring.datasource.hibernate.order_updates=true	

spring.datasource.jpa.properties.hibernate.generate_statistics=fasle
spring.datasource.jpa.properties.hibernate.jdbc.batch_size=4
sspring.datasource.jpa.properties.hibernate.order_inserts=true
spring.datasource.jpa.properties.hibernate.order_updates=true	
