#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/rule_engine_2?useSSL=false
spring.jpa.show-sql: true

spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
# c3p0  pooling
hibernate.c3p0.max_size=20
hibernate.c3p0.min_size=5
hibernate.c3p0.idle_test_period=600
hibernate.c3p0.acquire_increment=1
hibernate.c3p0.timeout=1800
hibernate.c3p0.max_statements=150

entitymanager.packagesToScan=com.tricon.rcm.db.entity
#Others
filter.log.enable=true

#jwt  
jwt.header=Authorization
jwt.secret=mySecretLocal
jwt.expiration=600000
jwt.route.authentication.path=/account/login
jwt.route.authentication.refresh=/refresh


spring.jpa.open-in-view=false
server.port=8081

scheduler.startcron=0 55 21 * * *

#Google Sheet related 
google.credential.folder=E:/Project/Tricon/files
google.client.secret=E:/Project/Tricon/files/client_secret.json

#rule engine
rcm.ruleengine.password=134568
rmc.auth.token=bcaf13e3-w507-4467-8e6e-7c0993fd445d
rmc.pullclaimurl=http://localhost:8080/fetch-claims
rmc.pullInsuranceUrl=http://localhost:8080/fetch-insurance
rcm.pullremoteliteurl=http://localhost:8080/remote-lite-details