spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.username=***
spring.datasource.password=***
spring.datasource.jdbc-url=***
#pooling
spring.datasource.maximum-pool-size=20
spring.datasource.minimum-idle=2
spring.datasource.max-lifetime=120
spring.jpa.show-sql: true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
# Find Properties using spring.datasource.hikari and then Remove "hikari" to access Prop.
#spring.datasource.hikari.auto-commit =true


spring.datasource.hikari.connection-timeout=60000


#JPA poolling https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes

entitymanager.packagesToScan=com.tricon.rcm.db.entity
#Others
filter.log.enable=true

#jwt  
jwt.header=Authorization
jwt.headerC=c
jwt.headerT=t
jwt.headerR=r
jwt.secret=mySecretLocal
jwt.expiration=600000
jwt.route.authentication.path=/account/login
jwt.route.authentication.refresh=/refresh


spring.jpa.open-in-view=false
server.port=8081
#sec min hours
scheduler.startcron=0 30 3 * * *
#(second (0-59))|(minute (0 - 59))|(hour (0 - 23))|(day of the month (1 - 31))|(month (1 - 12)|(or JAN-DEC)) (day of the week (0 - 7)) (0 or 7 is Sunday, or MON-SUN)
scheduler.posting.startcron=0 30 2 * * *
#Google Sheet related 
google.credential.folder=/opt/project/tricon/files
google.client.secret=/opt/project/tricon/files/client_secret.json

#rule engine
               
rmc.auth.token=bcaf13e3-w507-4467-8e6e-9c0993fd445d
rmc.pullclaimurl=https://caplineruleengine.com/fetch-claims
rmc.pullInsuranceUrl=https://caplineruleengine.com/fetch-insurance
rcm.pullremoteliteurl=https://caplineruleengine.com/remote-lite-details
rcm.diagnosticurl=https://caplineruleengine.com/diagnostic_check_for_rcm
rcm.ivfdataurl=https://caplineruleengine.com/ivf-data-for-rcm
rcm.claimESdataurl=https://caplineruleengine.com/claim-data-form-es
rcm.tpESdataurl=https://caplineruleengine.com/tp-data-form-es
rcm.tpIdsESdataurl=https://caplineruleengine.com/tp-ids-form-es
rcm.claimAppointmenturl=https://caplineruleengine.com/claim-appointment-date
rcm.reconcillationquery=https://caplineruleengine.com/reconcillation-query
#pagination
data.totalRecordperPage=30
data.archiveClaims.totalRecordperPage=300
data.searchClaims.totalRecordperPage=200
#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support.rcmtool@caplineservices.com
spring.mail.password=zjvtyxoqatvhysug
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true

app.email.from=support.rcmtool@caplineservices.com

#send email enable/disable
app.email.userRegistration=true
app.email.forgotPassword=true
#google captcha credential

captcha.url=https://www.google.com/recaptcha/api/siteverify
captcha.secret.key=6LdMb8ckAAAAAHIbrKWHROQ4F5Qo1Vmvgj5cmiWw

#login path without captcha 
jwt.route.testing.authentication.path=/account/l_abc

#server
rcm.serverdomain=https://caplinedentalbilling.com
#xslt
rcm.xslt.path=/opt/project/xml/
list_claim.xslt.file=/opt/project/xml/pdfformat_list_claim.xslt
claim.xslt.file=/opt/project/xml/claim.xslt
Issue_claim.xslt.file=/opt/project/xml/pdfformat_Issue_Claim.xslt
Claim_Details.xslt.file=/opt/project/xml/pdfformat_Claim_Details.xslt
Production.xslt.file=/opt/project/xml/pdfformat_Production_Data.xslt
Pendancy.xslt.file=/opt/project/xml/pdfformat_Pendancy_Data.xslt
All_Pendancy.xslt.file=/opt/project/xml/pdfformat_AllPendancy_Data.xslt
Tp_Plan_Link.xslt.file=/opt/project/xml/pdfformat_TpPlan_Data.xslt
Ivf_Link.xslt.file=/opt/project/xml/pdfformat_Ivf_Data.xslt
others_team.xslt.file=/opt/project/xml/pdfformat_others_team_work.xslt
search_claim.xslt.file=/opt/project/xml/pdfformat_search_claim.xslt
#save attachments
app.attachment.dir.path=/opt/project/attachments
spring.servlet.multipart.max-file-size=100000000
spring.servlet.multipart.file-size-threshold=200000000
#EOBLINK
eoblink.folder=/opt/project/pdf