#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/rule_engine_2?useSSL=false
#pooling
spring.datasource.maximum-pool-size=20
spring.datasource.minimum-idle=2
spring.datasource.max-lifetime=120
spring.jpa.show-sql: true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
# Find Properties using spring.datasource.hikari and then Remove "hikari" to access Prop.
#spring.datasource.hikari.auto-commit =true


spring.datasource.hikari.connection-timeout=60000


#JPA poolling https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes

entitymanager.packagesToScan=com.tricon.rcm.db.entity
#Others
filter.log.enable=true

#jwt  
jwt.header=Authorization
jwt.secret=mySecretLocal
jwt.expiration=600000
jwt.route.authentication.path=/account/login
jwt.route.authentication.refresh=/refresh


spring.jpa.open-in-view=false
server.port=8081

scheduler.startcron=0 17 22 * * *

#Google Sheet related 
google.credential.folder=E:/Project/Tricon/files
google.client.secret=E:/Project/Tricon/files/client_secret.json

#rule engine
rmc.auth.token=bcaf13e3-w507-4467-8e6e-7c0993fd445d
rmc.pullclaimurl=http://localhost:8080/fetch-claims
rmc.pullInsuranceUrl=http://localhost:8080/fetch-insurance
rcm.pullremoteliteurl=http://localhost:8080/remote-lite-details
rcm.diagnosticurl=http://localhost:8080/diagnostic_check_for_rcm